### ISSUE TITLE
Unable to Create Deployment in Testnet-02 Via Console

### ISSUE THREAD

**Issue by chainzero** [akash-network/console-old#123]
Unable to create a deployment via Akash Console on testnet-02 network.  Details below and within explained screenshots.

-  First screen shot shows settings successfully configured for testnet-02
-  Second screen shows that when user navigates to Deployments > blank page is presented which does not update > blank screen again on refresh or exiting paging and re-entering
-  Based on browser logs - included in screen shot - appears that React cannot find the /new-deployment route associated component

<img width="1266" alt="image" src="https://github.com/akash-network/console/assets/82888608/f6fc38bc-42b1-43a8-b7f7-b9e8e9f52b8f">

<img width="1272" alt="image" src="https://github.com/akash-network/console/assets/82888608/c28dd852-6554-4a6c-b647-a2558c537de2">

**Comment by anilmurty** [comment]
For context - the reason this is happening is because of the partial refactor for the new landing page https://github.com/akash-network/console/pull/110 - 

In other words the link from the new deployment button points to the old page but if you manually go to https://staging-console.akash.network/landing/node-deployment you'll see the new deployment page

**Comment by anilmurty** [comment]
Additional context for what we're trying to accomplish with the route changes https://github.com/akash-network/console/issues/112 and https://github.com/akash-network/console/issues/100
