### ISSUE TITLE
Add support for using custom RPC node and chain ID

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#7]
Currently the RPC node and chain ID are hard-coded into the build file. To enable safer testing, it would be ideal if these values could be picked up from the ENV and overridden in the UI.

**Describe alternatives you've considered**

**Additional context**
Additionally, the meta files could used to get the data for the chain: (eg: https://github.com/ovrclk/net/blob/master/mainnet/meta.json)

**Comment by boz** [comment]
It's OK to do this after GA IMHO

**Comment by anilmurty** [comment]
moved to post-ga

**Comment by anilmurty** [comment]
update, Mar 2nd: @jtary working on implmenting this in the UI under settings.

**Comment by anilmurty** [comment]
@jtary - could you please create two issues (for the things we talked about in our weekly sync) and reference them here? Even PR references (if you closed them) are fine:
- Found another bug where a new provider’s info doesn’t show up if the provider was spun up while the user session hasn’t been refreshed.
- Also made code changes to the data model for the whole app so that data recoil data (that stores data between pages) refreshes more often.
